config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :plays do
    resources :reviews
  end
  root 'plays#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :plays
end

app/models/play.rb
class Play < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :reviews
  
  has_attached_file :play_img, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :play_img, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :play
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :plays
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_play, only: [:edit, :update, :destroy]

  def index
    if (params[:category].blank?)
      @plays = Play.all.order('created_at DESC')
    else
      category = Category.find_by(name: params[:category])
      @plays = []
      if !category.blank?
        @plays = Play.where(category_id: category.id).order('created_at DESC')
      end
    end
  end

  def show
    @play = Play.find(params[:id])
    if @play.review.blank?
      @average_review = 0
    else
      @average_review = @play.reviews.average(:rating).round(2)
    end
  end

  def new
    @play = current_user.plays.build
    @categories = Category.all.map{ |c| [c.name, c.id ] }
  end

  def create
    @play = current_user.plays.build(play_params)
    if @play.save
      redirect_to root_path
    else
      redner 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id ] }
  end

  def update
    if @play.update(play_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

  def play_params
    params.require(:play).permit(:title, :description, :director, :category_id, :play_img, :trailer_url)
  end

  def find_play
    @play = current_user.plays.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, excepts: [:show]
  before_action :find_play, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.build(review_params)
    @review.play = @play

    if @review.save
      redirect_to play_path(@play)
    else
      'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_play
    @play = Play.find(params[:play_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Broadway</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Broadway!', root_path, class: 'navbar-brand' %>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filter <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>">
                  <%= link_to category.name, plays_path(category: category.name), class: 'link' %>
                </li>
              <% end %>
            </ul>
          </li>
          <% if user_signed_in? %>
            <li><%= link_to 'Add Play', new_play_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% else %>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <% if notice %>
      <p class='notice'><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class='alert'><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
  <%= f.input :play_img, label: 'Play Image' %>
  <%= f.association :category, prompt: 'Select Category' %>
  <%= f.input :title, label: 'Play Title' %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.input :trailer_url %>
  <%= f.button :submit %>
<% end %>

app/views/plays/edit.html.erb
<h1> Edit Broadway Play</h1>
<%= render 'form' %>

app/views/plays/index.html.erb
<section class='plays'>
  <h1 class='current_category'><%= params[:category] %></h1>
  <% if @plays.count == 0 %>
    <h3>There are no plays in this category</h3>
  <% else %>
    <div class='row'>
      <% @plays.each do |play| %>
        <div class='col-md-2 col-sm-3 col-xs-12'>
          <%= link_to play_path(play) do %>
            <div class='play-item'>
              <%= image_tag play.play_img.url, class: 'img-responsive play-image' %>
              <div class='play-title'>
                <%= link_to play.title, play_path(play) %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/plays/new.html.erb
<h1> New Broadway Play</h1>
<%= render 'form' %>

app/views/plays/show.html.erb
<div class='row'>
  <div class='col-lg-6 col-md-7 text-center'>
    <% if !@play.trailer_url.blank? %>
      <iframe src="<%= @play.trailer_url %>?autoplay=false&width=480" width="480" height="270" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" frameborder="no" scrolling="no"></iframe>
    <% else %>
      <%= image_tag @play.play_img.url, class: 'img-responsive play-image' %>
    <% end %>
  </div>
  <div class='col-lg-6 col-md-5'>
    <div class='play-info'>
      <h2 class='play-title'><%= @play.title %></h2>
      <h3 class='play-director'><em>From: </em><b><%= @play.director %></b></h3>
      <% if @play.category %>
        <h4 class='play-category'><%= @play.category.name %></h4>
      <% end %>
      <div class='play-average-rating' data-score="<%= @average_review %>"></div>
      <div class='play-reviews-count'></div>
      <p class='play-description'><%= @play.description %></p>
    </div>
  </div>
</div>

<div class='reviews'>
  <h1>Reviews</h1>
  <%= render @play.reviews %>
  <%= link_to 'Add Review', new_play_review_path(@play), class: 'btn btn-default' %>
</div>


<% if user_signed_in? && current_user.id == @play.user_id %>
  <div class='links btn-group'>
    <%= link_to 'Edit', edit_play_path(@play), class: 'btn btn-link' %>
    <%= link_to 'Destroy', play_path(@play), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for([@play, @play.reviews.build]) do |f| %>
  <div id='rating-input'>
    <label>Rating</label>
    <br>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, class: 'btn btn-default' %>
<% end %>

<script>
  $('#rating-input').raty({
    path: '/assets/raty/lib/images',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class='review'>
  <div class='review-rating' data-score="<%= review.rating %>"></div>
  <p class='review-comment'><%= review.comment %></p>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/raty/lib/images'
  });
</script>

app/views/reviews/new.html.erb
<div class='col-md-10 col-md-offset-1'>
  <div class='new-review-form'>
    <h1>Post Review</h1>
    <%= render 'form' %>
  </div>
</div>